version: "3.7"

services:
  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hhscraper_db
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  postgresql_data: