version: "3.7"

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.5
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgresql_data: